language: python
python:
  - "3.8"
# command to install dependencies
install:
  - curl https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.deb > hugo.deb
  - dpkg hugo.deb
# command to run tests
script: hugo
